import { MD3LightTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#6366f1',
    primaryContainer: '#e0e7ff',
    secondary: '#8b5cf6',
    secondaryContainer: '#f3e8ff',
    tertiary: '#06b6d4',
    tertiaryContainer: '#cffafe',
    surface: '#ffffff',
    surfaceVariant: '#f1f5f9',
    background: '#f8fafc',
    error: '#ef4444',
    errorContainer: '#fecaca',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#1e1b4b',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#581c87',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#164e63',
    onSurface: '#1f2937',
    onSurfaceVariant: '#6b7280',
    onBackground: '#1f2937',
    onError: '#ffffff',
    onErrorContainer: '#7f1d1d',
    outline: '#d1d5db',
    outlineVariant: '#e5e7eb',
    inverseSurface: '#374151',
    inverseOnSurface: '#f9fafb',
    inversePrimary: '#a5b4fc',
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
};